### ISSUE TITLE
Scale down by 1 is getting triggered for wrong rules.

### ISSUE THREAD

**Issue by Akhil-Nair-ML** [maplelabs/opensearch-scaling-manager#496]
Scale down by 1 is getting triggered for wrong rules.
Rules used:
```yaml
- task_name: scale_down_by_1
      operator: AND
      rules:
        - metric: CpuUtil
          limit: 30
          stat: COUNT
          decision_period: 720
          occurrences_percent: 95
        - metric: HeapUtil
          limit: 30
          stat: COUNT
          decision_period: 720
          occurrences_percent: 95
        - metric: RamUtil
          limit: 45
          stat: COUNT
          decision_period: 720
          occurrences_percent: 95
        - metric: DiskUtil
          limit: 50
          stat: COUNT
          decision_period: 720
          occurrences_percent: 95
```
The disk utilization was above 75% and it should not trigger a scale down due to AND operator.

We should change the logic where occurrences is calculated. The operator for scale down should be changed.
