### ISSUE TITLE
Scale down task evaluation 

### ISSUE THREAD

**Issue by Shrinidhi-P-ML** [maplelabs/opensearch-scaling-manager#83]
```
task_name: scale_down_by_1
  operator: OR
  rules:
  - metric: cpu
    limit: 25
    stat: AVG
    decision_period: 180
```
scale_down_by_1 task is recommended for avg cpu 54.8 which is above the limit.
